### ISSUE TITLE
BGP metrics

### ISSUE THREAD

**Issue by bl0m1** [bluecmd/fortigate_exporter#100]
I was playing around with the exporter and really like this project.

However when creating a dashboard I realised that I was missing some BGP metrics, more specifically:
* BPG peer state
* Routes received and advertised (and if possible if the routes is used AKA. best path)

There might even be more that I'm not thinking about?

If you like the idea I can give it a shot implementing and if it works out creating a PR.

**Comment by bluecmd** [comment]
Hi!

Yes, definitely - that is something we should have.

Regarding how to contribute - you can look at older PRs, but we recently completed a refactor of the code base so things have moved around.

The gist of it is:
- Find the API to query by either using the secret Fortinet documentation that is hard to get, or look at the web UI what requests are being sent when you look at the thing you are interested in. You can also use `cmdb` style commands to get things like CLI data if needed.
- When you have identified the API queries, you create `testdata` files (like [this](https://github.com/bluecmd/fortigate_exporter/blob/master/pkg/probe/testdata/link-monitor.jsonnet) one) with the content of a response from your Fortigate - redact what you feel you want to redact (serial numbers are common for people to redact). Make sure to include the API URL you used in the top so other people can update the file for future versions.
- Add the metric to the code, like [this](https://github.com/bluecmd/fortigate_exporter/blob/master/pkg/probe/system_status.go#L11).
- Make a [test](https://github.com/bluecmd/fortigate_exporter/blob/6ae5263c32740c970bc5cf538d271936a32e08cc/pkg/probe/system_status_test.go#L11) that uses the jsonnet file you created earlier. These tests look 99% identical to eachother, with the only difference being what jsonnet file to hook in to what URLs.

I had a quick look, and these APIs look interesting:
 - `/api/v2/monitor/router/ipv4?vdom=*` (could be too much data?)
 - `/api/v2/monitor/router/ipv6?vdom=*` (could be too much data?)
 - `/api/v2/cmdb/router/bgp/?datasource=1&with_meta=1&vdom=*`

Getting the output of e.g. `get router info bgp neighbors` would be nice, but not sure what cmdb or monitor api would be useful for that.

**Comment by bluecmd** [comment]
Reopened for adding more metrics

**Comment by bl0m1** [comment]
Metrics are now added in master and is available in 1.8.0. Closing this issue :)
