### ISSUE TITLE
API monitor/firewall/policy6 seems to have moved in 6.4.x

### ISSUE THREAD

**Issue by hbermudez-stratio** [bluecmd/fortigate_exporter#11]
Hi:

I'm trying to run with the "-insecure" flag but always have the error "Response code was 404":
```
2020/10/06 09:29:29 Loaded 3 API keys
2020/10/06 09:29:29 Fortigate exporter running, listening on ":9710"
2020/10/06 09:29:36 Error: Response code was 404, expected 200
2020/10/06 09:29:36 Probe of "https://xxx.xxx" failed, took 0.038 seconds
2020/10/06 09:29:40 Error: Response code was 404, expected 200
2020/10/06 09:29:40 Probe of "https://xxx.xxx" failed, took 0.029 seconds
```

I have conectivity and the machine can access without problem to the 443 tcp port. 
¿Meaby is the Fortigate version? I have the same issue with 6.4.1 and 6.4.2.
I'm using the -insecure flag.

Thanks

Ps: is the first time I post an Issue in GitHub, sorry if I did something wrong.

**Comment by bluecmd** [comment]
Can you change https://github.com/bluecmd/fortigate_exporter/blob/2b4ec1b9ae86fc0b9baf84a2408a05a9fddde948/forti_token_client.go#L71 to something like `return fmt.Errorf("Get %+v: Response code was %d, expected 200", req, resp.StatusCode)`?

It should give you more information. It could potentially log sensitive data so be careful where you save the output.

**Comment by hbermudez-stratio** [comment]
Hi again:

`2020/10/13 08:03:44 Error: Get &{Method:GET URL:https://xxx.xxx/api/v2/monitor/firewall/policy6/select?vdom=* Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Authorization:[Bearer XXX]] Body:<nil> GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:xxx.xxx Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000096180}: Response code was 404, expected 200
2020/10/13 08:03:44 Probe of "https://xxx.xxx" failed, took 0.115 seconds`

I tried to login with curl from the terminal and suscess without problems. 

Thanks

**Comment by bluecmd** [comment]
When you're logged in in a normal browser, can you try to visit that URL? The `https://xxx.xxx/api/v2/monitor/firewall/policy6/select?vdom=*` that is.

**Comment by hbermudez-stratio** [comment]
Sure!

`{
  "path":"firewall",
  "name":"policy6",
  "action":"select",
  "serial":"FG4H0EXXXXXXXXXX",
  "version":"v6.4.2",
  "build":1723,
  "status":"error",
  "http_status":404
}`

**Comment by bluecmd** [comment]
Very interesting. What model of Fortigate is this?
My naive guess would be that the platform doesn't support v6 - but that seems quite far-fetched?

**Comment by hbermudez-stratio** [comment]
I test it on:
- FortiGate 400E: v6.4.2
- FortiGate 201E: v6.4.1

They change how login, now in the docu Forti say you have to acces with the URL:
https://<YOUR-FORTGATE-ADDRESS>/api/v2/cmdb/firewall/address/?access_token=<YOUR-API-TOKEN>

I guess thats the problem :)

**Comment by bluecmd** [comment]
Fortigates have two ways to get information, cmdb and the monitor API. Do you have a source that says that this monitor API call was deprecated?

**Comment by hbermudez-stratio** [comment]
You are right!
![image](https://user-images.githubusercontent.com/31400842/95857121-70c3d780-0d5b-11eb-87c1-a12c6c1ca48b.png)
So it isn't deprecated.

**Comment by deathstone** [comment]
I have the same problem.
Forti 500E : v6.4.2
Forti 81F : v6.4.2

**Comment by drpixel972** [comment]
Hello,

I've the same issue on 60E wih 6.4.3 version, but it works on 50E with 6.2.6.
I guess the issue is a change in the 6.4 API 

Best Regards,

**Comment by bluecmd** [comment]
Sorry that I have been unable to respond to this - I am currently not near my Fortigate device/lab so I haven't been able to try to reproduce the issue.

I am happy to review any fix / PR if anyone wants to fix it themselves though!

**Comment by drpixel972** [comment]
Just another point, a 60E with 6.2.5 firmware does works so the issue is really the 6.4 firmware.

I've comment out the ipv6 probe in the source code and the probe is now fine.

So right now the ipv6 seems to be the only thing that has moved.

We need to get the newest API guide to easily find the newest path (if it exist) ... 

[apiv2-monitor-firewall.txt](https://github.com/bluecmd/fortigate_exporter/files/5605159/apiv2-monitor-firewall.txt)

**Comment by bluecmd** [comment]
Hi folks. I made a pull request (#22) - if anyone could give it a test and see if it works for them that would be really awesome!

I have tested using 6.4 Fortigate-VM, so tests using hardware fortigates would be extra appreciated.

**Comment by deathstone** [comment]
Hello,

I wanted to test with version 6.4 but how do I put the insecure parameter with docker-compose?

**Comment by drpixel972** [comment]
Hello,
I no longer have the issue.
That said, I don't have any IPV6 policy, so while the probe is now working, I can't say if the IPV6 metrics are available.
Best Regards 
Christophe

**Comment by bluecmd** [comment]
@hbermudez-stratio You listed some hardware fortigates, would you be able to test?

**Comment by drpixel972** [comment]
I'll double check and update my RPM package give me a few minutes.

**Comment by hbermudez-stratio** [comment]
Hi:

I have only one error:
`2020/12/30 12:19:42 Error: Response code was 404, expected 200 (path: "api/v2/monitor/firewall/policy6/select")
2020/12/30 12:19:42 Probe of "https://xxx.xxx" failed, took 0.078 seconds
`
But I got the rest of the metric without problems.
Today I will update all firewalls to 6.4.4, so tomorrow I will say if it works :)

If you need something, just tell me.

Thanks a lot!

**Comment by drpixel972** [comment]
it's also ok for me :-)
FG60E with 6.4.4

**Comment by bluecmd** [comment]
Very nice.

@hbermudez-stratio Do you get that error with using the `64-ipv6-policy` branch? That branch should detect a 6.4 or newer fortigate and not query `policy6`.

**Comment by hbermudez-stratio** [comment]
Give me a few minutes, I will try it.

**Comment by hbermudez-stratio** [comment]
Hi again @bluecmd 

I have the same issue:
```
2020/12/30 12:58:32 Error: Response code was 404, expected 200 (path: "api/v2/monitor/firewall/policy6/select")
2020/12/30 12:58:32 Probe of "https://deuterio.int.stratio.com" failed, took 0.077 seconds
```

**Comment by drpixel972** [comment]
Hello,
With the other branch, it works .
2020/12/30 14:08:06 Loaded 1 API keys
2020/12/30 14:08:06 Fortigate exporter running, listening on ":9710"
2020/12/30 14:09:19 Probe of "https://xxx.xxx.xxx.xxx:8443" succeeded, took 0.526 seconds

probe_duration_seconds 0.526397619
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 1

Best Regards,

**Comment by bluecmd** [comment]
@drpixel972 Thank you for testing, glad it works! Let me know if you discover any other 6.4 issues

> Hi again @bluecmd
> 
> I have the same issue:
> 
> ```
> 2020/12/30 12:58:32 Error: Response code was 404, expected 200 (path: "api/v2/monitor/firewall/policy6/select")
> 2020/12/30 12:58:32 Probe of "https://deuterio.int.stratio.com" failed, took 0.077 seconds
> ```

@hbermudez-stratio Hum, that's odd. As you can see here, the check added in that branch is to look at if the machine is using 6.4 or newer and if so not request `policy6` but rather use `policy` instead.

https://github.com/bluecmd/fortigate_exporter/blob/4bea9ebed7d4c54dea8dff5852a4528d8c47a04e/probe.go#L375-L395

The most likely cause I can tell here is that you by mistake tried with the `master` branch. Alternatively you might be running some some odd version maybe? I assume 6.4.0 or newer?

**Comment by hbermudez-stratio** [comment]
Hi:

As you said I used the wrong branch, my bad. 
Now I don't have any error.

Thanks a lot and sorry for the problems.

PS: Happy new year! I had a few full days :)

**Comment by bluecmd** [comment]
Perfect! Thanks for testing, Sorry this took so long for me to fix!

Enjoy!
