### ISSUE TITLE
move fortigate-key.yaml out of /opt to allow Kubernetes Secret mounts

### ISSUE THREAD

**Issue by kifeo** [bluecmd/fortigate_exporter#12]
Kubernetes only support mounting of full directories, not specific files for Secrets mounts.

Mounting the whole /opt as read only for Secrets makes the container not start.

Please change it to some directory not used by the system, like /config so this does not interfere with the mount.
Thanks

The kubelet error is here for reference: 
`  failed to start container "fortigate-exporter": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"mkdir /opt/fortigate_exporter: read-only file system\"": unknown`

**Comment by bluecmd** [comment]
Sounds good to me! Should be fixed now with your PR (thanks!)
