### ISSUE TITLE
Unlimited request for REST API login failure

### ISSUE THREAD

**Issue by toydogs** [bluecmd/fortigate_exporter#134]
Hello
I've been working on an exporter lately.
The firewall equipment was blocked from logging on due to an infinite connection attempt by the exporter during Fortigate's reset.
Is there a function to stop the function if it fails after several attempts?
Thank you.

**Comment by secustor** [comment]
Not any that I'm aware of as this is behavior which has been also reported by users of this project. 

You probably find better answers on [/r/fortinet](https://www.reddit.com/r/fortinet/) or in the Fortinet dev forums.

Closing as it is not relevant to this project.

**Comment by bluecmd** [comment]
To elaborate, no - there is no way to tell the exporter to "give up". It will try with the configured credentials every time it receives a poll request.

I know the pain of the lockout behavior but as @secustor was pointing at, I don't think the exporter should keep state between scrapes.

We do however sanity check the API credentials by requesting system status. If that fails, the rest of the probing will not occur. In the past we blasted away all requests and caused lock-outs much much sooner. At least now it should be 1 request per scrape.

**Comment by toydogs** [comment]
Thank you!
