### ISSUE TITLE
polling does not work with Fortigates with certificates signed with custom CA

### ISSUE THREAD

**Issue by kifeo** [bluecmd/fortigate_exporter#14]
workaround :
I forked the repository and replaced the ca-certificates.crt in the Dockerfile.
COPY ca.crt /etc/ssl/certs/ca-certificates.crt

Error is :
`2020/10/08 13:29:53 Loaded 1 API keys

2020/10/08 13:29:53 Fortigate exporter running, listening on ":9710"

2020/10/08 13:30:57 Error: Get "https://fgt.domain.net/api/v2/monitor/system/status": x509: certificate signed by unknown authority

2020/10/08 13:30:57 Probe of "https://fgt.domain.net" failed, took 0.148 seconds
`

**Comment by bluecmd** [comment]
You should be able to provide your own ca-certificates.crt using `SSL_CERT_FILE` environment variable as far as I know.
Can you try putting your custom CA root somewhere as a custom file and setting that environment variable?

**Comment by kifeo** [comment]
indeed, missed this, I will try it and tell you

**Comment by kifeo** [comment]
I tried, and it does not work :
Error: Get "https://fgt.domain.net/api/v2/monitor/system/status": x509: certificate signed by unknown authority

**Comment by drpixel972** [comment]
Hello,

If the CA is trusted by the system, then it works. 
For exemple in CentOS you put the CA certificates in /etc/pki/ca-trust/source/anchors/ then you issue the command update-ca-trust.

After that you should not have the  "x509: certificate signed by unknown authority" error message.

Best Regards,

**Comment by bluecmd** [comment]
You can now use both `-extra-ca-certs` as well as the panic button `-insecure` if you want to skip validation altogether.
This should close this, let me know if you have any further issues!
