### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by waleedmagdy** [bluecmd/fortigate_exporter#145]
Target is down on prometheus 
and I am getting error : `Get "http://[::1]:9710/probe?target=https%3A%2F%2F172.21.16.1": context deadline exceeded`

on the CLI :` Error: API connectivity test failed, Get "https://172.21.16.1/api/v2/monitor/system/status": context canceled`

what exactly is it referring to?

thanks to help

**Comment by AlexNisulescu** [comment]
Did you somehow solved this problem? I have the same problem and have no ideea how to solve it..

**Comment by AlexNisulescu** [comment]
> Did you somehow solved this problem? I have the same problem and have no idea how to solve it..

I solved it. My problem was that I was using the wrong port to connect to the device.

**Comment by waleedmagdy** [comment]
Yes this will give you the same error, and good that you figure it out.

You need to check both the reachability and Latency for the Fortigate from the Exporter.
for me I extend the scrape timeout from Prometheus to give some time for fortigate_exporter to scrape the metrics.

**Comment by bluecmd** [comment]
Seems this is no longer an issue
