### ISSUE TITLE
Bug : Unable to fetch data after forcing tls1.2 on fortigate

### ISSUE THREAD

**Issue by BeArchiTek** [bluecmd/fortigate_exporter#152]
Hello,

After forcing tls1.2+ on fortigate, the exporter is not able to get the data.

Steps to reproduce :

1- change firewall configuration 
```
config global
  config system global
    set admin-https-ssl-versions tlsv1-2
  end
end
```

2- Check prometheus logs.

Best regards,

**Comment by BeArchiTek** [comment]
I guess adding
```
tc. MinVersion = tls.VersionTLS12
```
after https://github.com/bluecmd/fortigate_exporter/blob/81adda5136cc5f9160c0ec7c9f10ccdcd63713a4/pkg/http/main.go#L52
could work.

**Comment by bluecmd** [comment]
I am not able to reproduce this. I added the suggested configuration to my Fortigate 61F running 7.0.6 and the exporter is able to fetch data just fine.

I verified with cURL that TLS 1.1 does not work, and TLS 1.2 works.

Is this still an issue with the latest builds @BeArchiTek ?

**Comment by BeArchiTek** [comment]
Hello,

Sorry for the late reply.
Didn't reproduced in 7.0.6 either.

(i anyone is reading that with the same issue, i was in 7.0.2)
