### ISSUE TITLE
Install fortigate_exporter

### ISSUE THREAD

**Issue by pavjke** [bluecmd/fortigate_exporter#153]
Hello, 
I'm newbie at Prometheus/exporters kitchen and I need help with installation of fortigate_exporter. As I know exporter must be installed at target system, but I can't install third party software at Fortigate hardware appliance. So where I must install fortigate_exporter? At some dedicated intermediate server between Prometheus and Fortigate appliance?

In this case workflow look like: Prometheus server communicate with fortigate_exporter which in turn communicate with Fortigate appliance? I understand correctly?

**Comment by bluecmd** [comment]
Yes, 100% correct. You can learn more about this way to use Prometheus at https://prometheus.io/docs/guides/multi-target-exporter/.

**Comment by pavjke** [comment]
Thank you so much for answer and for additional information. An issue can be closed.
