### ISSUE TITLE
Debug mode for issue diagnosis

### ISSUE THREAD

**Issue by imakiro** [bluecmd/fortigate_exporter#154]
Hi,

I can't seem to be able to run the project, as no metrics nor logs are returned (no errors in docker logs)
Is there a debug mode to verify where the issue might comme from? 
I used the -insecure flag to no avail
Fortigate ver : 7.0.2, read only full access REST API user
Latest build from docker

**Comment by bluecmd** [comment]
The log contains both successful and unsuccessful scrapes, can you post how the log looks like? It should at least say which version of the exporter it is starting.

**Comment by imakiro** [comment]
`:~/fortigate_exporter# docker logs 260d1006bc0d1313273d1abbfb1392d2d0714745c5dee51cb244c19ca02551c5
2021/11/30 15:47:22 FortigateExporter 1.14.1 ( 81adda5 )
2021/11/30 15:47:22 Loaded 1 API keys
2021/11/30 15:47:22 Fortigate exporter running, listening on ":9710"
`

That's it ...

**Comment by bluecmd** [comment]
Every probe logs **at least** the message `Probe of "https://xyz" failed/succeeded, took X.Y seconds`.

Are you sure your scrape requests are not blocked on the way to the exporter?

**Comment by imakiro** [comment]
CF. my original ticket message : how would I know?

**Comment by Haibread** [comment]
Hi,

It appears that I'm having the exact same issue.

When I run  `./fortigate-exporter.linux.amd64 -auth-file fortigate-key.yaml` , I am only getting 3 lines of logs, even if I wait for a few minutes :
```
2021/12/02 16:13:46 FortigateExporter 1.14.1 ( 81adda5 )
2021/12/02 16:13:46 Loaded 1 API keys
2021/12/02 16:13:47 Fortigate exporter running, listening on ":9710"
```
The page `http://ip:port/metrics` is only showing go, process, promhttp and only one fortigate_exporter_build_info related metrics

Let me know if you need more informations.

Thanks

**Comment by bluecmd** [comment]
The `/metrics` endpoint is only for internal metrics on the exporter itself - in order to scrape the actual device you have to follow the README and set it up as a blackbox-style exporter, specifically this part: https://github.com/bluecmd/fortigate_exporter#prometheus-configuration

**Comment by imakiro** [comment]
That's the piece of information I missed being not too familliar with prometheus, thank you !
