### ISSUE TITLE
arm64 docker image 

### ISSUE THREAD

**Issue by ndamian10** [bluecmd/fortigate_exporter#155]
Hi,

root@raspberrypi:~#  docker run -d -p 9710:9710 -v $PWD/fortigate-key.yaml:/config/fortigate-key.yaml quay.io/bluecmd/fortigate_exporter:master
Unable to find image 'quay.io/bluecmd/fortigate_exporter:master' locally
master: Pulling from bluecmd/fortigate_exporter
c49dfa386f08: Pull complete
42fe67539471: Pull complete
20d5dcf83435: Pull complete
Digest: sha256:71438189b5ae3240fe1da13d24c7688317be01acb87ef16969d2e0268b11c60e
Status: Downloaded newer image for quay.io/bluecmd/fortigate_exporter:master
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
4d79556fbf1fa717214a68e77659520f7bbd0083e55c93ea2fec1ea4438c38db

It would be awesome to dispose arm64 images.

Thanks and great job!

**Comment by farconada** [comment]
same problem here:

```
Building prometheus_fortigate_exporter
Step 1/12 : FROM quay.io/prometheus/golang-builder:1.16.2-base as builder
 ---> e17d808dbe53
Step 2/12 : WORKDIR /build
 ---> Using cache
 ---> b88a4f7f7989
Step 3/12 : COPY . .
 ---> 3a9ff4995ecd
Step 4/12 : RUN go get -v -t -d ./...
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 880dbf1e746d
standard_init_linux.go:228: exec user process caused: exec format error
ERROR: Service 'prometheus_fortigate_exporter' failed to build : The command '/bin/sh -c go get -v -t -d ./...' returned a non-zero code: 1

```

**Comment by farconada** [comment]
with  this builder image works
FROM golang:1.17 as builder
