### ISSUE TITLE
Didn't understand how to install 

### ISSUE THREAD

**Issue by Weathmious** [bluecmd/fortigate_exporter#160]
Hello,

I have my prometheus server on a debian 11 server that is installed and connected to Grafana and I would like to receive data from my two fortigate firewalls. The problem is that I can't install this exporter. I put the zip on my server, but then I don't understand how to use it. Can you help me? Thanks

**Comment by PPACI** [comment]
Hello
You have to 
1. Create an API Key for you Fortigate
2. Create the fortigate-key.yaml file https://github.com/bluecmd/fortigate_exporter#usage
3. Start (manually or create a service in systemD) the exporter. Use `-auth-file` to pass the file create in 2. https://github.com/bluecmd/fortigate_exporter#available-cli-parameters
4. Add a prometheus target to scrape your exporter. https://github.com/bluecmd/fortigate_exporter#prometheus-configuration
5. Create your dashboard in Grafana.
