### ISSUE TITLE
ap_status broken in FortiOS 7.0.x

### ISSUE THREAD

**Issue by morcha134** [bluecmd/fortigate_exporter#163]
After upgrading from FortiOS 6.4.4 to FortiOS 7.0.3 we were getting probe_success=0 and an error 502 from wifi_ap_status.go

We fixed by changing line 43 from:

if err := c.Get("api/v2/monitor/wifi/ap_status", "vdom=*&start=0&count=1000", &response); err != nil {
to:
if err := c.Get("api/v2/monitor/wifi/ap_status", "vdom=*", &response); err != nil {

By the way the Fortinet API documentation states "No parameters" for the call to api/v2/monitor/wifi/ap_status both in 6.4.4 and 7.0.3.
They probably removed support for start and count parameters without warning because it was not supposed to be supported.

**Comment by ZnarreZ** [comment]
I guess you missing a wildcard after _vdom=_ in both lines:

After replacement:
`if err := c.Get("api/v2/monitor/wifi/ap_status", "vdom=*", &response); err != nil {`
