### ISSUE TITLE
Fortigate sensors

### ISSUE THREAD

**Issue by ChyronDare** [bluecmd/fortigate_exporter#187]
Hi! 

With the new update, sensor scraping was added. 
We have a couple of fortigates that we would like to monitor the temperatures with, these are mostly 40F, 100F and 200F units. 
When using the CLI to check the temperature we get results back, unfortunately with the exporter we get the code 404 response. 
![image](https://user-images.githubusercontent.com/111047676/184094704-14deac0b-007d-4a5c-b5e5-eefa6ee755b0.png)

Is there any way to get this working with the exporter?

**Comment by BeArchiTek** [comment]
The API endpoint api/v2/monitor/system/sensor-info is not supported on smaller firewall like 60F and 100F.

**Comment by kifeo** [comment]
is there a way to disable certain API calls in the config ?

**Comment by BeArchiTek** [comment]
👋 @kifeo 

You can use the `exclude` keyword in your config file to not poll some API endpoint on a per device based.
Is that what you are looking for ?

**Comment by kifeo** [comment]
Sorry @BeArchiTek , I found it in the README:
  probes:
    exclude:
      - System/SensorInfo
      
Thanks !
