### ISSUE TITLE
Include metrics for HA member

### ISSUE THREAD

**Issue by secustor** [bluecmd/fortigate_exporter#19]
As HA members, at least in our case have no own IP address, some stats for the HA peers should be also included.    

Initially this is what I would need: 
- `fortigate_ha_member_info{hostname="fw01", serial="FGXXXXXXX", vclusterid="0"} 1` 
   path: /monitor/system/ha-peer

later there could be performance metrics like
- `fortigate_ha_member_sessions{hostname="fw01"} 100`
- `fortigate_ha_member_packets_total{hostname="fw01"} 100000`
- `fortigate_ha_member_virus_events_total{hostname="fw01"} 100`
- `fortigate_ha_member_network_usage_ratio{hostname="fw01"} 0.1`
- `fortigate_ha_member_bytes_total{hostname="fw01"} 1000000`
- `fortigate_ha_member_ips_events_total{hostname="fw01"} 100`
- `fortigate_ha_member_cpu_usage_ratio{hostname="fw01"} 0.1`
- `fortigate_ha_member_memory_usage_ratio{hostname="fw01"} 0.1`
path: /monitor/system/ha-statistics

I'm interested in implementing this.

**Comment by bluecmd** [comment]
Hi!

That sounds good, happy to accept a PR for the metric.
Do you need guidance to implement this?
