### ISSUE TITLE
uptime for passive ha node

### ISSUE THREAD

**Issue by pbousek** [bluecmd/fortigate_exporter#192]
Hello,
is it possible to get information about node uptime for both devices in HA pairs?

I assume that fortigate_last_reboot_seconds returns uptime for active member. But I think that it will be useful to have information that passive node performed restart so something like fortigate_ha_last_reboot_seconds metric.

Thanks 
Petr

**Comment by bluecmd** [comment]
You can create this in PromQL using existing metrics (member role & last reboot), so there is no need to have a new metric for this

**Comment by pbousek** [comment]
I have metric fortigate_ha_member_has_role that tell me if node is master or not but metric fortigate_last_reboot_seconds is related to whole cluster, not single members ... so how can I get uptime of passive member?

**Comment by bluecmd** [comment]
Scrape all members of the cluster, not just the master :-)

**Comment by pbousek** [comment]
ok, so thats the point, I thought that all can be scraped over HA address, thanks a lot ;-)
