### ISSUE TITLE
Fork for Fortigate Proxy

### ISSUE THREAD

**Issue by damhau** [bluecmd/fortigate_exporter#199]
Hello everybody,

First, thanks a lot for this exporter.

If anybody is interested I've made a fork to support the Fortinet proxy: https://github.com/damhau/fortiproxy_exporter
I only had to change the parsing of the memory because the api is returning the memory as a string in the Fortiproxy (eg: changed Current float64 to Current float64 `json:",string"`).
And I've also disabled a few metric like bgp, etc...

Cheers,

Damien

**Comment by bluecmd** [comment]
Hi Damien!

Very cool, thanks for sharing :-)
