### ISSUE TITLE
HA sync status

### ISSUE THREAD

**Issue by dusod** [bluecmd/fortigate_exporter#200]
Hi Bluecmd,

can you please add status of devices sync? Similar what we see at System->HA->Status FortiGate's GUI. 

If such a thing already exist, please point me to it.

Thank you 

Dusan

**Comment by lcostes** [comment]
agree with dusod, these informations would be very helpful
Primary / secondary member, uptime, state changed
thanks for all the job done

**Comment by bluecmd** [comment]
Merging with https://github.com/bluecmd/fortigate_exporter/issues/226
