### ISSUE TITLE
API connectivity test failed

### ISSUE THREAD

**Issue by ryantrung** [bluecmd/fortigate_exporter#201]
Hi Bluecmd,

After run command 
./fortigate_exporter --insecure -auth-file ~/fortinet_config/fortigate-key.yaml

I got the error : 

**Error: API connectivity test failed, Response code was 404, expected 200 (path: "api/v2/monitor/system/status")**

Please show me how to do

Thanks so much

**Comment by bluecmd** [comment]
Too little data provided, going to close this
