### ISSUE TITLE
Certificates metrics

### ISSUE THREAD

**Issue by renatomdg** [bluecmd/fortigate_exporter#21]
Hey, is it possible to get certificate metrics? if its not supported by the exporter (at moment) but possible to get that metrics from the firewall i can send a PR to that, there's a "guide" to show where to implement the support for new metrics?
Thanks for that work :)

**Comment by bluecmd** [comment]
Hi!

Yes, this can be added for sure.

I have this script that I use to install certificates: https://github.com/bluecmd/fortigate/blob/master/update-fortigate-cert - so getting them using the API is possible. It needs to be parsed and then exported as a metric.

I am open for reviewing pull requests to add this!

There is no guide, but you might be able to look at older pull requests where people have successfully added metrics such as HA.

**Comment by secustor** [comment]
What kind metrics are you looking for regarding certificates?    
The API endpoint returns a lot of data, so I don't think it makes sense to implement each and every detail. Below an example API response.

This is a to a single certificate shortened response.
``` 
# api/v2/monitor/system/available-certificates
{
  "http_method":"GET",
  "results":[
    {
      "name":"Fortinet_CA_SSL",
      "source":"factory",
      "comments":"This is the default CA certificate the SSL Inspection will use when generating new server certificates.",
      "range":"global",
      "exists":true,
      "is_ssl_server_cert":true,
      "is_proxy_ssl_cert":true,
      "is_general_allowable_cert":true,
      "is_default_local":false,
      "is_built_in":true,
      "is_wifi_cert":false,
      "is_deep_inspection_cert":true,
      "has_valid_cert_key":true,
      "key_type":"RSA",
      "key_size":2048,
      "is_local_ca_cert_strict":true,
      "is_local_ca_cert":true,
      "type":"local-ca",
      "status":"valid",
      "valid_from":1472285182,
      "valid_from_raw":"2016-08-27 08:06:22  GMT",
      "valid_to":1787904382,
      "valid_to_raw":"2026-08-28 08:06:22  GMT",
      "signature_algorithm":"SHA256",
      "subject":{
        "C":"US",
        "ST":"California",
        "L":"Sunnyvale",
        "O":"Fortinet",
        "OU":"Certificate Authority",
        "CN":"FGT61E4XXXXXXXX",
        "emailAddress":"support@fortinet.com"
      },
      "subject_raw":"C = US, ST = California, L = Sunnyvale, O = Fortinet, OU = Certificate Authority, CN = FGT61E4XXXXXXXX, emailAddress = support@fortinet.com",
      "issuer":{
        "C":"US",
        "ST":"California",
        "L":"Sunnyvale",
        "O":"Fortinet",
        "OU":"Certificate Authority",
        "CN":"FGT61E4XXXXXXXX",
        "emailAddress":"support@fortinet.com"
      },
      "issuer_raw":"C = US, ST = California, L = Sunnyvale, O = Fortinet, OU = Certificate Authority, CN = FGT61E4XXXXXXXX, emailAddress = support@fortinet.com",
      "fingerprint":"F9:96:25:CC:E0:E9:08:F7:1C",
      "version":3,
      "is_ca":true,
      "serial_number":"28:D7:XX:XX",
      "ext":[
        {
          "name":"X509v3 Basic Constraints",
          "data":"CA:TRUE",
          "critical":false
        }
      ],
      "q_path":"vpn.certificate",
      "q_name":"local",
      "q_ref":5,
      "q_static":true,
      "q_type":155
    }
  ],
  "vdom":"root",
  "path":"system",
  "name":"available-certificates",
  "status":"success",
  "serial":"FGT61E4XXXXXXXX",
  "version":"v6.2.3",
  "build":1066
}
```

**Comment by bluecmd** [comment]
I'd say that likely what people are looking for is certificates in use that will expire soon.

Thus, maybe we can start with something like:

```
fortigate_certificate_expiry{name="Xyz"} 169....
# I assume q_ref is the amount of things referencing the certificate
fortigate_certificate_references{name="Xyz"} 5
```

That way one could set up monitoring for certs expiring while avoiding false positives if they are not used.

It would probably also be nice to add a label if the certificate is manually added or Fortigate built-in - I'll see if I can look at my Fortigate to see what field is different for those.

**Comment by secustor** [comment]
`q_ref` has following description in the API documentation   
`The CMDB reference count for this certificate.`     
Therefore I would go with `fortigate_certificate_cmdb_references`.

Is `fortigate_certificate_valid` in your example simply an interpretation for the current time is bigger than `valid_from` and smaller than `valid_to`?  If yes I think it would be better to simply expose both unix timestamps and allow the users to write queries for those.      
e.g. `fortigate_certificate_valid_from_seconds{...} < time() || fortigate_certificate_valid_to_seconds{...} > time() + 24 * 60 * 60`     
to be alarmed if the certificate is not valid yet or will be no longer valid in the next 24h.

If I would see `vdom=""`, the first thing I would think is that this is a bug or empty field in Fortinet.    
What do you think about adding a scope label and filling vdom with `<global>`.  

To summarize your example metrics would look like this: 

```
fortigate_certificate_valid_from_seconds{name="Xyz",source="user", scope="global", vdom="<global>"} 169.....
fortigate_certificate_valid_from_seconds{name="Test",source="user", scope="vdom", vdom="bluecmd"} 169.....
fortigate_certificate_valid_to_seconds{name="Xyz",source="user", scope="global", vdom="<global>"} 169.....
fortigate_certificate_valid_to_seconds{name="Test",source="user", scope="vdom", vdom="bluecmd"} 169.....

fortigate_certificate_cmdb_references{name="Xyz",source="user",scope="global", vdom="<global>"} 5
fortigate_certificate_cmdb_references{name="Xyz",source="user",scope="vdom", vdom="bluecmd"} 2
fortigate_certificate_cmdb_references{name="Xyz",source="user",scope="vdom", vdom="root"} 0
fortigate_certificate_cmdb_references{name="Xyz",source="user",scope="vdom", vdom="something"} 2
fortigate_certificate_cmdb_references{name="Test",source="user",scope="vdom", vdom="bluecmd"} 1
``` 
This would allow for example `count(fortigate_certificate_cmdb_references{scope="vdom})` to get number of certificates installed in vdoms. It would be possible with an empty vdom too, but I think this is more streamlined regarding the user experience.

Thoughts?

**Comment by bluecmd** [comment]
Good on the naming, I like it.

I also like the `scope`, I can see how an empty label can look odd without that. In PromQL a label set to nothing is the same as it not being present, so with the distinction of having "scope=global" I think we should either drop the vdom label for those, or have "vdom=''". I am not a huge fan of magic strings that can bite people.

Wdyt?

**Comment by secustor** [comment]
I haven't been aware that PromQL handles empty values like that. In that case I see no problem with `vdom=""`. 

For the status a info metric would be probably better fitting like `nodue_uname_info` from the node exporter.     
e.g. `fortigate_certificate_info{name="Xyz",source="user",scope="global", vdom="", status="pending", type="local-cer"} 1`      

Using joins then the user can query all expiry dates for CA certs for example

**Comment by bluecmd** [comment]
Indeed, the empty label is a bit of an advanced use case, but you can see examples like this: https://stackoverflow.com/questions/51293895/how-to-display-all-metrics-that-dont-have-a-specific-label or https://github.com/prometheus/prometheus/issues/494.

The `_info` seems like a good way to do this, I like it. That way we can hook on things like fingerprint and other stuff in the future if any users file feature requests for them.
