### ISSUE TITLE
problem to recieve metrics

### ISSUE THREAD

**Issue by DanielJohansson1976** [bluecmd/fortigate_exporter#217]
Hi

I have problem to get metrics from my fortigate fw
I only see this kind of metrics.

Container running I see this log message:
What I´m I missing?

Regards

Daniel
 
  
2023/05/03 21:28:37 Loaded 1 API keys
2023/05/03 21:28:37 Fortigate exporter running, listening on ":9710"

# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 10
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.15.4"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.650808e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.650808e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.44482e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 237
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 0
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 3.992976e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.650808e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 6.4167936e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 2.58048e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 3293
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 6.4167936e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.6748416e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 0
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 3530
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 3472
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 36856
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 49152
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.473924e+06

**Comment by bluecmd** [comment]
Hi! Check https://github.com/bluecmd/fortigate_exporter#prometheus-configuration

**Comment by DanielJohansson1976** [comment]
Hi, thanks for your answer. But I don't see any metrics with name fortigate when I surf against my container/metrics.
So I guess something is wrong?

Daniel

**Comment by DanielJohansson1976** [comment]
I only  see go metrics.

**Comment by thenodon** [comment]
@DanielJohansson1976 you should use the `/probe` endpoint not `/metrics`  https://github.com/bluecmd/fortigate_exporter#prometheus-configuration

**Comment by DanielJohansson1976** [comment]
Thanks, Now I recieve this:

curl 'https://fortigate_exporter.sds.io/probe?target=https://fortigate.sds.io&token=xxxxx&profile=fortigate'

# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.041923755
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0

Any more tips?
Thanks for your help.

**Comment by DanielJohansson1976** [comment]
2023/05/04 15:02:06 Loaded 2 API keys
2023/05/04 15:02:06 Fortigate exporter running, listening on ":9710"
2023/05/04 15:03:12 Probe request rejected; error is: No API authentication registered for "https://fortigate.XXXX.io"
2023/05/04 15:03:30 Error: Response code was 404, expected 200
2023/05/04 15:03:30 Probe of "https://172.28.17.1" failed, took 0.186 seconds
2023/05/04 15:05:33 Error: Response code was 404, expected 200
2023/05/04 15:05:33 Probe of "https://172.28.17.1" failed, took 0.181 seconds

# HELP fortigate_cpu_usage_ratio Current resource usage ratio of system CPU, per core
# TYPE fortigate_cpu_usage_ratio gauge
fortigate_cpu_usage_ratio{processor="0"} 0
fortigate_cpu_usage_ratio{processor="1"} 0
fortigate_cpu_usage_ratio{processor="2"} 0
fortigate_cpu_usage_ratio{processor="3"} 0
# HELP fortigate_current_sessions Current amount of sessions, per IP version
# TYPE fortigate_current_sessions gauge
fortigate_current_sessions{protocol="ipv4"} 774
fortigate_current_sessions{protocol="ipv6"} 0
# HELP fortigate_memory_usage_ratio Current resource usage ratio of system memory
# TYPE fortigate_memory_usage_ratio gauge
fortigate_memory_usage_ratio 0.46
# HELP fortigate_vdom_cpu_usage_ratio Current resource usage ratio of CPU, per VDOM
# TYPE fortigate_vdom_cpu_usage_ratio gauge
fortigate_vdom_cpu_usage_ratio{vdom="root"} 0
# HELP fortigate_vdom_current_sessions Current amount of sessions, per VDOM and IP version
# TYPE fortigate_vdom_current_sessions gauge
fortigate_vdom_current_sessions{protocol="ipv4",vdom="root"} 790
fortigate_vdom_current_sessions{protocol="ipv6",vdom="root"} 0
# HELP fortigate_vdom_memory_usage_ratio Current resource usage ratio of memory, per VDOM
# TYPE fortigate_vdom_memory_usage_ratio gauge
fortigate_vdom_memory_usage_ratio{vdom="root"} 0.46
# HELP fortigate_version_info System version and build information
# TYPE fortigate_version_info gauge
fortigate_version_info{build="1396",serial="FGT40FTK21099NC3",version="v7.2.4"} 1
# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.180845745
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0

One step forward.

**Comment by p-v-a** [comment]
could you try to run exporter with http debug?
`GODEBUG=http2debug=1 ./fortigate-exporter -auth-file fortigate-key.yaml -insecur`
what I found is there a change between firmware 7.0.x and 7.2.x which breaks exporter. seems there is no more /api/v2/monitor/switch-controller/managed-switch at the very least. may be more.

**Comment by thenodon** [comment]
It is interesting that Fortinet change the api contract between minor versions. I agree that pagination should be done instead of just a larger number - my bad.

**Comment by p-v-a** [comment]
> It is interesting that Fortinet change the api contract between minor versions. I agree that pagination should be done instead of just a larger number - my bad.

I don't think it was a api contract change tbh. I couldn't find api/v2/monitor/switch-controller/managed-switch endpoint in fortinet docs, it always been api/v2/monitor/switch-controller/managed-switch/status. probably it was working for a while, until fortigate have fixed it.

**Comment by bluecmd** [comment]
@p-v-a is there an action to be done here? Should the above patch be merged? If so, care to move it to a PR?

To me I'm having trouble grokking if there are things left to be done here, so I'll close this issue.
