### ISSUE TITLE
Not getting network routes and BGP (IPv4 and IPv6) connection metrics

### ISSUE THREAD

**Issue by faizansyed66** [bluecmd/fortigate_exporter#222]
Hi Team,
I want to monitor the network routes and BGP (IPv4 and IPv6) connection metrics, but I am not getting these metrics from the node exporter. Is it due to permission issue? but I have given all the required permission. Below are the curl logs and the container logs of my node exporter.

```
sudo docker logs d28
2023/05/26 10:51:05 Warning: Response code was 404, expected 200 (path: "api/v2/monitor/system/sensor-info")
2023/05/26 10:51:05 Probe of "https://d2c-ucpe-fw-01-mgmt.sharedtcs.net" failed, took 0.807 seconds
2023/05/26 10:52:05 Warning: Response code was 404, expected 200 (path: "api/v2/monitor/system/sensor-info")
2023/05/26 10:52:05 Probe of "https://d2c-ucpe-fw-01-mgmt.sharedtcs.net" failed, took 0.601 seconds
```

Below is the few last line output of Curl for node exporter with Fortigate as a target.

```
curl 'localhost:9710/probe?target=https://d2c-ucpe-fw-01-mgmt.sharedtcs.net'
# TYPE fortigate_wifi_fabric_clients gauge
fortigate_wifi_fabric_clients{vdom="root"} 0
fortigate_wifi_fabric_clients{vdom="ucpe"} 0
# HELP fortigate_wifi_fabric_max_allowed_clients Maximum number of clients which are allowed to connect
# TYPE fortigate_wifi_fabric_max_allowed_clients gauge
fortigate_wifi_fabric_max_allowed_clients{vdom="root"} 0
fortigate_wifi_fabric_max_allowed_clients{vdom="ucpe"} 0
# HELP probe_duration_seconds How many seconds the probe took to complete
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.597747199
# HELP probe_success Whether or not the probe succeeded
# TYPE probe_success gauge
probe_success 0
```

Request your advise here. @bluecmd

**Comment by bluecmd** [comment]
What Fortigaten version are you running? BGP metrics are only supported on 7.x

**Comment by faizan-syed** [comment]
> What Fortigaten version are you running? BGP metrics are only supported on 7.x

Sorry for late reply , We were running version lower than 7.x , recently its upgraded to 7.x we are able to view the BGP metrics now but the Routes (like number of connected routes , BGP , static routes) these info is not visible

**Comment by bluecmd** [comment]
I'll close this issue, if the other metrics are still missing open a new issue and include what the API response is and what metric you expected to see.
