### ISSUE TITLE
Error: API connectivity test failed, Response code was 429, expected 200

### ISSUE THREAD

**Issue by samfaunt** [bluecmd/fortigate_exporter#223]
Trying to deploy the export to monitor my 60F but seem to be getting this error over and over. 
Error: API connectivity test failed, Response code was 429, expected 200 (path: "api/v2/monitor/system/status")

I read some other people that have reported this issue but seems to be no resolution. 

if i visit https://10.99.22.1/api/v2/monitor/system/status?access_token=tokenhere  i get an API response and returns data.

i tried a curl with this command. which is suggested this is how the exporter does the request.

curl -vvv -k -H "Authorization: tokenhere "  "https://10.99.22.1/api/v2/cmdb/firewall/address/"

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<p>Additionally, a 401 Unauthorized
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
* Connection #0 to host 10.99.22.1 left intact
```

wonder if anyone knows what could be going on or if I'm doing anything wrong?
i'm running forgate 7.4.0.

FYI i'm running these commands on the same box that has the exporter installed on it.

Thanks!

**Comment by thenodon** [comment]
One additional thing. Your will typical see 429 if you have tried to login to many times with the wrong credentials. 429 is status on a rate limit `429 Too Many Requests`.

**Comment by bluecmd** [comment]
Closing this because of no update from @samfaunt
