### ISSUE TITLE
Random occurences of context cancelled

### ISSUE THREAD

**Issue by deggja** [bluecmd/fortigate_exporter#225]
Hello!

We have been using your fortigate exporter for a while and it is working great. We are seeing some random occurences of context cancelled error messages appearing in the log. Like the following example:

```
2023/06/09 10:48:05 Error: Get "https://random.com/api/v2/monitor/log/fortianalyzer?vdom=*": context canceled
2023/06/09 10:48:05 Error: Get "https://random.com/api/v2/monitor/log/fortianalyzer-queue?vdom=*": context canceled
2023/06/09 10:48:05 Error: Get "https://random.com/api/v2/monitor/log/current-disk-usage?vdom=*": context canceled
```

After this, the probe itself reports that it has failed. Usually this is around the 10 second mark.

On the next scrape a couple of minutes later it is returning data as expected without any issues and the probe succeeds. Do you/anyone have any idea why this is happening? Cant seem to find anything about any timeout around 10 seconds, and the default scrapeTimeout seems to be 30.

```
ScrapeTimeout: flag.Int("scrape-timeout", 30, "max seconds to allow a scrape to take")
```

This is probably not a issue/bug with the exporter, but I could not find anywhere to discuss this so I'm opening this instead.

Thanks for the awesome product btw 🚀

**Comment by bluecmd** [comment]
Hi!

Thanks for the praise, it's good to know the project is liked :-).

As for the context cancellation - one thing I can think of straight away is if you have set your Prometheus instance to time out after 10 seconds. That could cause the request to be closed and the context terminated, at least in my head without digging around.

**Comment by deggja** [comment]
@bluecmd Thanks for the response! Fortunately or unfortunately, depending on how you look at it, you're right 🤦 

Not sure how I missed it, but like you said, it was due to a global timeout in Prometheus that overruled the config for the targets that got cancelled.

**Comment by khol** [comment]
Hello
what fimeware version are you running on firewall (assuming it's a fw).
we experience similar behavior after going from 6.4.9 -> 7.0.12.
There is a lack of data points from the metric data due to timeout, however there are sporadic metric losses in the graphs.

did it get better after you increased the timeout?

**Comment by deggja** [comment]
> Hello what fimeware version are you running on firewall (assuming it's a fw). we experience similar behavior after going from 6.4.9 -> 7.0.12. There is a lack of data points from the metric data due to timeout, however there are sporadic metric losses in the graphs.
> 
> did it get better after you increased the timeout?

Unfortunately, I'm not responsible for the HW and was working together with a colleague on this. Yes, it was a firewall, but other than that I dont know much sadly.

At some point we did see some missing data points as well, so it might be a general issue on the newest version.
