### ISSUE TITLE
Add support for used ips / port block allocations of a sourcenat rule

### ISSUE THREAD

**Issue by 33Fraise33** [bluecmd/fortigate_exporter#231]
Hello,

Would it be possible to add support to show the amount of free port block allocations of an ip pool. 
This is availble at the following ap and retuns the following items: 

`/api/v2/monitor/firewall/ippool?vdom=*&access_token=<token>`

I am mainly interested in: 
`used`: amount of port blocks used
`total`: amount of port blocks available
`available`(OPTIONAL): percentage (but not really needed as it can be calculated from 100-used/total)
`natip_in_use`: amount of ips in the pba in use
`natip_total`: amount of ips available in the pba pool

```
[
    {
        "http_method": "GET",
        "results": {
            "PBA_NAME": {
                "name": "PBA_NAME",
                "blocks": 8,
                "block_size": 128,
                "fixed_port": false,
                "pba_per_ip": 472,
                "used": 10,
                "total": 118472,
                "available": 99.991561889648438,
                "clients": 10,
                "natip_in_use": 1,
                "natip_total": 251
            }
        },
        "vdom": "Hotspot",
        "path": "firewall",
        "name": "ippool",
        "action": "",
        "status": "success",
        "serial": "serialhere",
        "version": "v7.0.11",
        "build": 489
    }
]    
```

a 1:1 nat looks like this: 
```
            "PUB_NAME": {
                "name": "PUB_NAME",
                "blocks": 1,
                "block_size": 60416,
                "fixed_port": true,
                "pba_per_ip": 1,
                "used": 1,
                "total": 1,
                "available": 0.0,
                "clients": 1,
                "natip_in_use": 1,
                "natip_total": 1
            },
```

**Comment by thenodon** [comment]
@33Fraise33 I think this is possible, of course  @bluecmd decide on what to be included in the end. I would recommend that you try to implement it and make a pull request. I should be straight forward even if you are new to GO. @bluecmd has created a nice design of the fortigate exporter so you can just copy one of the "modules", e.g. https://github.com/bluecmd/fortigate_exporter/blob/master/pkg/probe/managed_switch.go in https://github.com/bluecmd/fortigate_exporter/tree/master/pkg/probe, and create your logic and then add it in https://github.com/bluecmd/fortigate_exporter/blob/master/pkg/probe/probe.go.

**Comment by 33Fraise33** [comment]
> @33Fraise33 I think this is possible, of course @bluecmd decide on what to be included in the end. I would recommend that you try to implement it and make a pull request. It should be straight forward even if you are new to GO. @bluecmd has created a nice design of the fortigate exporter so you can just copy one of the "modules" as a starting point, e.g. https://github.com/bluecmd/fortigate_exporter/blob/master/pkg/probe/managed_switch.go in https://github.com/bluecmd/fortigate_exporter/tree/master/pkg/probe, and create your logic and then add it in https://github.com/bluecmd/fortigate_exporter/blob/master/pkg/probe/probe.go.

I did already implement some items in #214 but it was not really up to spec + it seems lots of MR's are currently stuck.

**Comment by bluecmd** [comment]
I'll try to make some time next week and go through the PRs that can be merged and try to review the ones that are pending. I appreciate people pushing for features, I've just been busy with other stuff.

**Comment by bluecmd** [comment]
The problem with PR #214 is that it's a large one with many smaller unralated things in it, making a minor issue in one of them block the whole PR.

I recommend you create a PR with this metric with tests, but nothing more. That way it should be an easy merge.

**Comment by 33Fraise33** [comment]
Hi @bluecmd I changed my PRs to be split up. I will now check if I can implement this feature request myself as well
