### ISSUE TITLE
License metrics 

### ISSUE THREAD

**Issue by kcbark** [bluecmd/fortigate_exporter#30]
We need to monitor VDOM licenses so that we know when to order more.

I’ve implemented vdom license metrics in #29  but adding other license info should be pretty straight forward.

**Comment by bluecmd** [comment]
Great stuff, thanks! I have reviewed the PR. Writing this comment to ack the issue and make sure Github sends me issue updates.

**Comment by bluecmd** [comment]
Closing this as #29 is merged
