### ISSUE TITLE
Provide Release artifacts and pre build Docker images

### ISSUE THREAD

**Issue by secustor** [bluecmd/fortigate_exporter#38]
To enable a easier start up for user we should pre-build Docker images and go binaries.    

This could be in the first step a simple image stream which follows the master branch and later on a full blown automatic releases e.g. with [semver-bot](https://github.com/semantic-release/semantic-release)

**Comment by bluecmd** [comment]
I set up quay.io for now as I have used it in the past.

We can switch to use something else if there is a community preference.

https://quay.io/repository/bluecmd/fortigate_exporter?tab=info

**Comment by secustor** [comment]
semantic-release would create following release: 

# 1.0.0 (2021-03-14)

### Bug Fixes

    * CI: semver configuration typo (d3c85ff (https://github.com/bluecmd/fortigate_exporter/commit/d3c85ff5d75d93774d5e830a80c4ccade9b44dba))
    * deps: update module github.com/prometheus/client_golang to v1.9.0 (d91e26d (https://github.com/bluecmd/fortigate_exporter/commit/d91e26d9e3f2725a863689441119d9a767d7320e))
    * deps: update module gopkg.in/yaml.v2 to v2.4.0 (44c6b4e (https://github.com/bluecmd/fortigate_exporter/commit/44c6b4e95c775bf2872c2640a8767c0de0ad4fa6))
    * probeVirtualWANPerf: change Array type from string to float64 (0ec28d1 (https://github.com/bluecmd/fortigate_exporter/commit/0ec28d1587c6215c7bbce747a888450417fff8a4))
    * add api path to ha-statistics.jsonnet (e17a64d (https://github.com/bluecmd/fortigate_exporter/commit/e17a64d555bbbf4abaf0a9cf81f4a7d6be191466))

### Features

    * CI: add semantic-release for auto creation of releases, for now in dryRun mode (4125c35 (https://github.com/bluecmd/fortigate_exporter/commit/4125c350fa0ceb234c2f7091fc9e2533f249d479))
    * CI: replace composite actions with inline steps (2f62f83 (https://github.com/bluecmd/fortigate_exporter/commit/2f62f832f133bf43c3c54b3c794bd5ebde002380))
    * CI: run go workflow on all branches except master (14f6979 (https://github.com/bluecmd/fortigate_exporter/commit/14f6979f7a383e9f1190197bca67a6b21c388ef8))
    * add go module (2198088 (https://github.com/bluecmd/fortigate_exporter/commit/21980881b6217b7a55a98ef4b08229ff3f678099))
    * implement certificate metrics (67743f0 (https://github.com/bluecmd/fortigate_exporter/commit/67743f0b957aabca182cbb90b6fc14674c53078e))
    * use float64 or int64 to prevent errors from too big numbers  (#57 (https://github.com/bluecmd/fortigate_exporter/issues/57)) (364aed8 (https://github.com/bluecmd/fortigate_exporter/commit/364aed825edf98e0f0317e24e47403ed0a3def7b))
    * Github Workflow: check if GO files are formatted (#51 (https://github.com/bluecmd/fortigate_exporter/issues/51)) (4e295f4 (https://github.com/bluecmd/fortigate_exporter/commit/4e295f41a51469631ba2432e26f824295f101ce9))
    * add SDWAN/VirtualWAN metrics (2f0c76c (https://github.com/bluecmd/fortigate_exporter/commit/2f0c76c43dfaf62be9bb40aa6e8a69425c316905))
    * implement ha statistics (4b031da (https://github.com/bluecmd/fortigate_exporter/commit/4b031da27b60bb5e37ebe8c2fee85e8d8f2a0d68))
    * implement link-monitor API (5495b55 (https://github.com/bluecmd/fortigate_exporter/commit/5495b55601aede6a7113dcb86d05e69cfd3202a5))
    * Dockerfile: split up CMD into ENTRYPOINT and CMD (#16 (https://github.com/bluecmd/fortigate_exporter/issues/16)) (9815820 (https://github.com/bluecmd/fortigate_exporter/commit/9815820b1fcc06cf9fa751cc3c24d270a867d41b))

https://github.com/bluecmd/fortigate_exporter/runs/2107674207?check_suite_focus=true#step:11:257

**Comment by bluecmd** [comment]
Looks good to me!

What are the naming conventions for commits we should use?

**Comment by secustor** [comment]
Yes exactly. 

I have also linked the format in the previous PR https://github.com/bluecmd/fortigate_exporter/pull/65

The defaults, which are in effect right now can be found here: https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js  

basically it is a tag followed by an optional scope and a message.  The `feat` tag leads to a new minor version and any other from angular described tag leads to a patch release. A breaking change leads to a new major version. This is signaled using the `breaking` tag.

**Comment by secustor** [comment]
Seems like quai.io hasn't build a tagged version of the docker image :thinking:
