### ISSUE TITLE
Enable Renovate auto dependency updates

### ISSUE THREAD

**Issue by secustor** [bluecmd/fortigate_exporter#42]
Renovate is an auto dependency update tool for multiple programming and scripting languages.    

It creates PRs if new GO libraries are available, which are locked at the moment using go mod.     
We are using it here internally as well as some bigger tech companies. 

Here is the install for the hosted variant: 
https://github.com/apps/renovate

https://github.com/renovatebot/renovate

Thoughts? 

Disclaimer: I'm a contributor there too ^^

**Comment by bluecmd** [comment]
Happy to try it out! Do I need to enable something somewhere, or can you enable it?

**Comment by secustor** [comment]
The repo does not show up In the installation wizard, because of that I guess only an `Owner` can do that.

**Comment by bluecmd** [comment]
I think I enabled it now, it has sent a PR to be reviewed at least: #44

**Comment by bluecmd** [comment]
I have to say, this is pretty neat :-).

Are we done here, or is there more to do?

**Comment by secustor** [comment]
Yeah I like it too. 

Jop that`s it. It will do now its thing and will update any compatible files.     
Later on if we have good enough unit tests we could do auto merges
