### ISSUE TITLE
Not receiving SD-WAN metrics

### ISSUE THREAD

**Issue by agesta23** [bluecmd/fortigate_exporter#43]
I have latest build with SD-WAN metrics added, however I'm not seeing sd-wan metrics them after scraping the target. 
Here is mine fortigate profile configuration: 

```
edit "monitor"
        set secfabgrp read
        set netgrp custom
        set fwgrp custom
        set vpngrp read
        set system-diagnostics disable
        config netgrp-permission
            set cfg read
        end
        config fwgrp-permission
            set policy read
        end
```

I wonder if something has to be changed in profile configuration?

**Comment by bluecmd** [comment]
From the SD-WAN PR it can be seen that the permissions required should be `"access_group": "netgrp.cfg",` which you have listed.

What version of FortiOS are you running?
If you go to https://your-fortigate-here.local/api/v2/monitor/virtual-wan/health-check?vdom=* when logged in as a user, does it show the health checks you are looking for?

**Comment by bluecmd** [comment]
I will list this as support until we have narrowed it down a bit.

**Comment by agesta23** [comment]
Yes, I do receive result

```
http_method | "GET"
-- | --
results | {…}
vdom | "root"
path | "virtual-wan"
name | "health-check"
status | "success"
serial | "*********"
version | "v6.4.2"
build | 1723
```

**Comment by bluecmd** [comment]
Would you be OK with sharing the .json results in full (censoring IPs and serials are of course OK)?
I am having a bit of trouble reading that output - and I am interested mainly of the structure of the results object.

**Comment by agesta23** [comment]
Sure. Here you go.
`[
  {
    "http_method":"GET",
    "results":{
      "AWS_US_SLA":{
        "port9":{
          "status":"up",
          "latency":112.75773620605469,
          "jitter":0.03916727751493454,
          "packet_loss":0,
          "packet_sent":24741283,
          "packet_received":24665286,
          "session":309,
          "tx_bandwidth":11419643,
          "rx_bandwidth":697136,
          "state_changed":1614233414,
          "sla_targets_met":[
            1
          ]
        },
        "port10":{
          "status":"up",
          "latency":100.31079864501953,
          "jitter":0.089132942259311676,
          "packet_loss":0,
          "packet_sent":24741283,
          "packet_received":24724974,
          "session":10007,
          "tx_bandwidth":32588134,
          "rx_bandwidth":159458598,
          "state_changed":1607412315,
          "sla_targets_met":[
            1
          ]
        }
      },
      "AWS_EU_SLA":{
        "port9":{
          "status":"up",
          "latency":30.875497817993164,
          "jitter":0.14193330705165863,
          "packet_loss":0,
          "packet_sent":24741283,
          "packet_received":24734234,
          "session":309,
          "tx_bandwidth":11419643,
          "rx_bandwidth":697136,
          "state_changed":1614233414,
          "sla_targets_met":[
            1
          ]
        },
        "port10":{
          "status":"up",
          "latency":29.78489875793457,
          "jitter":0.57146674394607544,
          "packet_loss":1,
          "packet_sent":24741283,
          "packet_received":24713582,
          "session":10013,
          "tx_bandwidth":32588134,
          "rx_bandwidth":159458598,
          "state_changed":1607412315,
          "sla_targets_met":[
            1
          ]
        }
      },
      "gitlab":{
        "port9":{
          "status":"up",
          "latency":35.57550048828125,
          "jitter":0.04386698454618454,
          "packet_loss":0,
          "packet_sent":7421632,
          "packet_received":3416877,
          "session":309,
          "tx_bandwidth":11419643,
          "rx_bandwidth":697136,
          "state_changed":1614233414,
          "sla_targets_met":[
          ]
        },
        "port10":{
          "status":"error"
        }
      },
      "GOOGLE_DNS":{
        "port9":{
          "status":"up",
          "latency":22.144998550415039,
          "jitter":0.01653289794921875,
          "packet_loss":0,
          "packet_sent":24741283,
          "packet_received":24728256,
          "session":309,
          "tx_bandwidth":11419643,
          "rx_bandwidth":697136,
          "state_changed":1614233414,
          "sla_targets_met":[
            1
          ]
        },
        "port10":{
          "status":"up",
          "latency":7.2254014015197754,
          "jitter":0.031633313745260239,
          "packet_loss":0,
          "packet_sent":24741283,
          "packet_received":24733843,
          "session":10017,
          "tx_bandwidth":32588134,
          "rx_bandwidth":159458598,
          "state_changed":1607412315,
          "sla_targets_met":[
            1
          ]
        }
      }
    },
    "vdom":"root",
    "path":"virtual-wan",
    "name":"health-check",
    "status":"success",
    "serial":"*****",
    "version":"v6.4.2",
    "build":1723
  }
]`

**Comment by bluecmd** [comment]
Thanks. Is there anything being mentioned in the output of the exporter? If there is a permissions issue, hopefully there would be a warning.

**Comment by agesta23** [comment]
Yeah, there is.

2021/03/02 13:52:24 Probe of "https://fortigate.local:4434" failed, took 1.332 seconds
2021/03/02 13:52:38 Error: json: cannot unmarshal number into Go struct field SLAMember.results.sla_targets_met of type string
