### ISSUE TITLE
Debug fortigate_interface_receive_bytes_total

### ISSUE THREAD

**Issue by yatanasov** [bluecmd/fortigate_exporter#54]
Hello,

Great work with the exporter ! We are observing the following missing data for irate with fortigate_interface_receive_bytes_total 
Naturally, the grafana dashboard graph is not working too, how do we debug this ? We believe it might be something with the way the exporter works. Please see bellow:

![metrics](https://user-images.githubusercontent.com/3897089/109982391-2808bd00-7d02-11eb-9259-63aaec2c6c4e.JPG)

Thank you!

**Comment by bluecmd** [comment]
Hello!

Could you include the logs from the exporter and what version of FortiOS you are running?

**Comment by yatanasov** [comment]
Hello :) 

That was exactly the issue ! Thank you very  much !
