### ISSUE TITLE
How to pass insecure cli flag to docker fortigate_exporter

### ISSUE THREAD

**Issue by MathiasOliveira** [bluecmd/fortigate_exporter#55]
I am currently running a fortigate_exporter intance on docker but I need it to ignore certificate errors, although i found a `-insecure` flag for CLI, I can't find a way to add that to the docker instance. Is it possible to do this?

**Comment by secustor** [comment]
You can add such parameters simply after the docker image in a run command 
`docker run quay.io/bluecmd/fortigate_exporter:master -insecure `    
Docker will attach all parameters after image to the entrypoint.
