### ISSUE TITLE
Getting response conde 429 from FortiGate, probe fails

### ISSUE THREAD

**Issue by umutkacar** [bluecmd/fortigate_exporter#58]
I get this error when I probe the FortiGate device like this;

`curl 'localhost:9710/probe?target=https://fortigateurl:4434'`

```
2021/03/12 13:07:27 Fortigate exporter running, listening on ":9710"
2021/03/12 13:07:56 Loaded 1 API keys
2021/03/12 13:07:56 Fortigate exporter running, listening on ":9710"
2021/03/12 13:09:07 Error: Response code was 401, expected 200 (path: "api/v2/monitor/system/status")
2021/03/12 13:09:07 Error: Response code was 401, expected 200 (path: "api/v2/monitor/system/resource/usage")
2021/03/12 13:09:07 Error: Response code was 429, expected 200 (path: "api/v2/monitor/system/resource/usage")
2021/03/12 13:09:08 Error: Response code was 429, expected 200 (path: "api/v2/monitor/firewall/policy/select")
2021/03/12 13:09:08 Error: Response code was 429, expected 200 (path: "api/v2/monitor/system/interface/select")
2021/03/12 13:09:09 Error: Response code was 429, expected 200 (path: "api/v2/monitor/vpn/ssl")
2021/03/12 13:09:09 Error: Response code was 429, expected 200 (path: "api/v2/monitor/vpn/ipsec")
2021/03/12 13:09:09 Error: Response code was 429, expected 200 (path: "api/v2/monitor/system/ha-statistics")
2021/03/12 13:09:09 Error: Response code was 429, expected 200 (path: "api/v2/monitor/license/status/select")
2021/03/12 13:09:10 Error: Response code was 429, expected 200 (path: "api/v2/monitor/system/link-monitor")
2021/03/12 13:09:13 Error: Response code was 429, expected 200 (path: "api/v2/monitor/virtual-wan/health-check")
2021/03/12 13:09:13 Error: Response code was 429, expected 200 (path: "api/v2/monitor/system/available-certificates")
2021/03/12 13:09:13 Probe of "https://fortigateurl:4434" failed, took 6.024 seconds
```

FortiGate ver.: v6.0.6 build0272 (GA)
Docker image used: quay.io/bluecmd/fortigate_exporter:master

Why do you think this could happen?

**Comment by secustor** [comment]
429 uses Fortinet to signal that your IP is blocked because of too much login attempts.

![image](https://user-images.githubusercontent.com/17493763/110949669-27e07100-8343-11eb-8a35-cf64abb6aeee.png)

I would check first that your API Token is valid and/or that your source IP of the exporter is whitelisted.

**Comment by bluecmd** [comment]
Indeed, the current behavior is that we assume the credential is valid and can actually block the requester IP if we are unable to login.

I will file an issue for improving this behavior, but ultimately yes this is a configuration error where the API token is not allowed to query the fortigate device.

**Comment by secustor** [comment]
Closing this as we haven't received any new questions and opened a feature request which should solve this in the future.
