### ISSUE TITLE
Monitoring Fortiswitch over a fortilink

### ISSUE THREAD

**Issue by ikiranreddy** [bluecmd/fortigate_exporter#60]
Hi Christian Svensson,

Can I use fortigate_exporter to monitor fortiswitches over a forlink?
can we expect this feature in your fortigate_exporter coming days.

Thanks,
Kiran Reddy

**Comment by bluecmd** [comment]
Hello. Currently it cannot, it was filed as a feature request in #15. I personally do not own any fortiswitches so I have been hesitant to add monitoring support for them as I would not know how people usually work with them and what metrics make sense.

If you want to help adding it that would be great - at the very least it would be useful to know what metrics you want in the linked issue.

I will close this as a duplicate now and refer to the other bug.

**Comment by ikiranreddy** [comment]
@bluecmd I just wanted to monitor Interface status and bandwidth utilization along with CPU/Memory. It is greater to see MCAG status and MCLAG-ICL and MCLAG-ISL status.

Please do let me know any information required from my end like configuration or any.
