### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by secustor** [bluecmd/fortigate_exporter#64]
To pull together all information regarding adding code to this project, we should add a `Contributing.md`. 

The content should contain at least following sections: 
 - How to build this project
 - metric best practices
 - links to resources 
 - allowed commit message styles and scopes

**Comment by secustor** [comment]
reference: https://github.com/bluecmd/fortigate_exporter/issues/100#issuecomment-877096726

**Comment by IMSdevsecu** [comment]
Now addressed in #141
