### ISSUE TITLE
Image build fails after after prometheus_client update

### ISSUE THREAD

**Issue by secustor** [bluecmd/fortigate_exporter#75]
After the upgrade of the prometheus_client dependency the Docker build fails.     
I have no access to the build logs, so I can not investigate here.

**Comment by bluecmd** [comment]
![image](https://user-images.githubusercontent.com/149442/111763770-ca987280-88a2-11eb-9580-3b42cd73d783.png)

**Comment by bluecmd** [comment]
After looking at this a bit it seems related to that Docker Hub added API limits end of 2020 which is now hitting Quay. One solution would be to not depend on Docker Hub for our golang:latest dependency, but I have not found a good replacement.

One possible one could be the Prometheus Golang Builder, https://quay.io/repository/prometheus/golang-builder, but it appears to be for building release binaries a bit differently than we have in mind. Still, might be able to use it as the base.
