### ISSUE TITLE
Cannot start the fortigate exporter

### ISSUE THREAD

**Issue by amitkatti** [bluecmd/fortigate_exporter#79]
For some reason I cannot use the binary:

Below is the output: 

_[root@netmonitor fortigate_exporter]# go build fortigate_exporter.go
go: github.com/prometheus/client_golang@v1.10.0 requires
        github.com/prometheus/common@v0.18.0 requires
        github.com/go-kit/kit@v0.10.0 requires
        github.com/casbin/casbin/v2@v2.1.2 requires
        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible: invalid pseudo-version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/dac3237ce23c7a321475df4e3bb8c7115ea5c093fdf9bc1798a57a9ef75ede77: exit status 128:
        fatal: git fetch-pack: expected shallow list_

What am I doing wrong?

**Comment by bluecmd** [comment]
Good day @amitkatti 

Could you let me know the output of `go version` and `uname -a`?

Finally, can you try building the exporter using `go build` (without arguments)?

**Comment by amitkatti** [comment]
Good day sir, thanks!

[root@netmonitor fortigate_exporter]# go version
go version go1.15.5 linux/amd64

[root@netmonitor fortigate_exporter]# uname -a
Linux netmonitor 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

go build still gives me the same error:

[root@netmonitor fortigate_exporter]# go build
go: github.com/prometheus/client_golang@v1.10.0 requires
        github.com/prometheus/common@v0.18.0 requires
        github.com/go-kit/kit@v0.10.0 requires
        github.com/casbin/casbin/v2@v2.1.2 requires
        github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible: invalid pseudo-version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/dac3237ce23c7a321475df4e3bb8c7115ea5c093fdf9bc1798a57a9ef75ede77: exit status 128:
        fatal: git fetch-pack: expected shallow list

**Comment by bluecmd** [comment]
Very good, thanks!

If possible could you try with Golang 1.16 or newer? I believe we have some things that might require Go 1.16 if nothing else.

**Comment by amitkatti** [comment]
Alright, that worked just fine. Thank you!
