### ISSUE TITLE
Certificates Workaround

### ISSUE THREAD

**Issue by amitkatti** [bluecmd/fortigate_exporter#82]
I am running some test environments and do not intend on creating https certificates for the web gui. Is there any workaround for this without getting https certificate?

[root@netmonitor bin]# systemctl status fortigate_exporter.service -l
● fortigate_exporter.service - Fortigate_Exporter
   Loaded: loaded (/etc/systemd/system/fortigate_exporter.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-04-07 20:16:53 GMT; 15min ago
 Main PID: 32683 (fortigate_expor)
   CGroup: /system.slice/fortigate_exporter.service
           └─32683 /usr/local/bin/fortigate_exporter -auth-file /etc/prometheus/fortigate_exporter/fortigate-key.yaml

Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/system/interface/select?vdom=*&include_vlan=true&include_aggregate=true": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/vpn/ssl?vdom=*": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/vpn/ipsec?vdom=*": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/system/ha-statistics": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/license/status/select": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/system/link-monitor?vdom=*": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/virtual-wan/health-check?vdom=*": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/system/available-certificates?scope=global": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Error: Get "https://192.168.10.151:8443/api/v2/monitor/firewall/load-balance?vdom=*&start=0&count=1000": x509: cannot validate certificate for 192.168.10.151 because it doesn't contain any IP SANs
Apr 07 20:32:10 netmonitor fortigate_exporter[32683]: 2021/04/07 20:32:10 Probe of "https://192.168.10.151:8443" failed, took 0.137 seconds

**Comment by bluecmd** [comment]
Hello, nice that you got it running.

Indeed, you can use either `-insecure` to totally disable CA checking for test setups, or `-extra-ca-certs` in order to specify extra CAs to trust.

**Comment by amitkatti** [comment]
Where do I use the -insecure command?

**Comment by amitkatti** [comment]
Beautiful. Thank you. Worked :)
