### ISSUE TITLE
Add test to ensure that new commits are using the correct format

### ISSUE THREAD

**Issue by bluecmd** [bluecmd/fortigate_exporter#87]
I forgot to set the correct commit format in #86 when squashing.

We should probably just require commits in the PR to be checked against the naming standard.

**Comment by secustor** [comment]
https://github.com/zeke/semantic-pull-requests

This could be a start.

**Comment by secustor** [comment]
https://github.com/apps/semantic-pull-requests

**Comment by bluecmd** [comment]
> https://github.com/apps/semantic-pull-requests

Added
