### ISSUE TITLE
Wifi metrics

### ISSUE THREAD

**Issue by kristenungdom** [bluecmd/fortigate_exporter#88]
the /api/v2/monitor/wifi should be included: 

/client 
"summary": "Retrieve a list of connected WiFi clients

/managed_ap
"summary": "Retrieve a list of managed FortiAPs.

/firmware
"summary": "Retrieve a list of current and recommended firmware for FortiAPs in use.

/list
"summary": "When FortiWiFi is in client mode, retrieve list of local WiFi networks.

/status
"summary": "When FortiWiFi is in client mode, retrieve status of currently connected WiFi network, if any.

/ap_status
"summary": "Retrieve statistics for all managed FortiAPs.

/interfering_ap
"summary": "Retrieve a list of interfering APs for one FortiAP radio.

/euclid
"summary": "Retrieve presence analytics statistics.

/rogue_ap
"summary": "Retrieve a list of detected rogue APs.

/spectrum
"summary": "Retrieve spectrum analysis information for a specific FortiAP.

/vlan-probe
"summary": "Retrieve the VLAN probe results.

**Comment by secustor** [comment]
Can you provide example API responses of the endpoints? 
Use the testdata folder as example.

**Comment by kristenungdom** [comment]
Added files for these responses:

/client
"summary": "Retrieve a list of connected WiFi clients

/managed_ap
"summary": "Retrieve a list of managed FortiAPs.

/firmware
"summary": "Retrieve a list of current and recommended firmware for FortiAPs in use.

/ap_status
"summary": "Retrieve statistics for all managed FortiAPs.

/interfering_ap
"summary": "Retrieve a list of interfering APs for one FortiAP radio.

/euclid
"summary": "Retrieve presence analytics statistics.

/rogue_ap
"summary": "Retrieve a list of detected rogue APs.

**Comment by secustor** [comment]
Can you confirm that you have uploaded the files? I don't see any file at your answer or the original issue.     

Do you have used maybe a file format which is not supported by Github? 
https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by kristenungdom** [comment]
No you are right, I had no upload rights so they ended up in my fork :)

Uploads are disabled.
File uploads require push access to this repository.

**Comment by secustor** [comment]
Can you eloaborate on what kind of metrics you want to see or maybe describe your use case? 

As the API endpoints are pretty broad, I want to prevent that we start the implementation and later see that we totally missed the target.

**Comment by kristenungdom** [comment]
I am adding the api endpoint query in https://github.com/kristenungdom/fortigate_exporter/tree/wifi/testdata

the interesting endpoints are ap_status, client and managed_ap, the same data can be collected in these like the other ones, maybe not the euclid (like people counter that could be interesting but there are too much data that I don't know what it means right now.) skipping the rouge_ap, interfering_ap and firmware for now.

Ok, starting with the https://xxx.xxx.xxx.xxx/api/v2/monitor/wifi/ap_status, the interesting and most basic metrics I believe are:

    "wtp_active":3,
    "wtp_down":0,
    "client_count":17,
Quite self explanatory.


And https://xxx.xxx.xxx.xxx/api/v2/monitor/wifi/client, data is separated on client level so the interesting parts are: 

"hostname":"XXX",
"signal":-75,
"wtp_name":"2nd Floor",
"data_rate_bps":58000000,
"wtp_bandwidth_Tx":"26 kbps",
"wtp_bandwidth_Rx":"404 kbps",
"wtp_bandwidth_TRx":"430 kbps",


The https://xxx.xxx.xxx.xxx/api/v2/monitor/wifi/managed_ap endpoint has a lot of different information per AP, clients per radio, bandwidth per radio and separate data for the uplink wired interface. 

"name":"1st Floor",
"ap_profile":"athome",
"mesh_uplink_intf_speed":1000,
"clients":3,
"os_version":"FP221E-v6.4-build0460",
"cpu_usage":8,
"mem_free":84416,
"mem_total":235216,

"radio":[
  {
    "radio_id":1,
    "oper_chan":11,
    "txpower":100,
    "client_count":0,

"wired":[
  {
    "interface":"lan1",
    "bytes_rx":8522738577,
    "bytes_tx":81464248708,
    "packets_rx":39750816,
    "packets_tx":66700986,
    "errors_rx":0,
    "errors_tx":0,
    "dropped_rx":14622,
    "dropped_tx":0,
    "collisions":0
  }
],
"wan_status":[
  {
    "interface":"lan1",
    "link_speed_mbps":1000,
    "carrier_link":true,
    "full_duplex":true
  }
],
