### ISSUE TITLE
collected metric error

### ISSUE THREAD

**Issue by stefen-jms** [bluecmd/fortigate_exporter#90]
When I access to the webpage http://localhost:9710/probe?target=https://my-fortigate', i got these errors occurred

8 error(s) occurred:
* collected metric "fortigate_ha_member_sessions" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > gauge:<value:1648 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_packets_total" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > counter:<value:4 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_virus_events_total" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_network_usage_ratio" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > gauge:<value:0.47 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_bytes_total" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > counter:<value:160 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_ips_events_total" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_cpu_usage_ratio" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "fortigate_ha_member_memory_usage_ratio" { label:<name:"hostname" value:"FGT60E-VEIGZ" > label:<name:"vdom" value:"root" > gauge:<value:0.6 > } was collected before with the same name and label values

But the log shows that I probed successfully
"Probe of "https://my-fortigate" succeeded, took 1.163 seconds"

the prometheus shows the  target state is down

**Comment by stefen-jms** [comment]
the fortigate_exporter version is 1.4.0 and my fortigate firmware is 6.2.7

**Comment by secustor** [comment]
Looks like you have configured both HA members with the same hostname. 

Can you share your API response from `curl -H "Authorization: Bearer ${API_TOKEN}" https://my-fortigate/api/v2/monitor/system/ha-statistics` ?

**Comment by stefen-jms** [comment]
> Looks like you have configured both HA members with the same hostname.
> 
> Can you share your API response from `curl -H "Authorization: Bearer ${API_TOKEN}" https://my-fortigate/api/v2/monitor/system/ha-statistics` ?

yes, there are two device configuring HA

here is the result of  curl -H "Authorization: Bearer ${API_TOKEN}" https://my-fortigate/api/v2/monitor/system/ha-statistics
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by stefen-jms** [comment]
> Looks like you have configured both HA members with the same hostname.
> 
> Can you share your API response from `curl -H "Authorization: Bearer ${API_TOKEN}" https://my-fortigate/api/v2/monitor/system/ha-statistics` ?

**Comment by bjolivot** [comment]
Same problem here, but with different hostname:

{
  "http_method":"GET",
  "results":[
    {
      "hostname":"xxxxFW01",
      "serial_no":"*****246",
      "tnow":27019567,
      "sessions":5279,
      "tpacket":67897519763,
      "vir_usage":0,
      "net_usage":0,
      "tbyte":22560700002315,
      "intr_usage":200,
      "cpu_usage":14,
      "mem_usage":71
    },
    {
      "hostname":"xxxxFW02",
      "serial_no":"*****690",
      "tnow":27018982,
      "sessions":4122,
      "tpacket":1,
      "vir_usage":0,
      "net_usage":0,
      "tbyte":40,
      "intr_usage":0,
      "cpu_usage":2,
      "mem_usage":67
    }
  ],
  "vdom":"root",
  "path":"system",
  "name":"ha-statistics",
  "status":"success",
  "serial":"*****3246",
  "version":"v6.0.5",
  "build":268
}
