### ISSUE TITLE
Problem with HA and fortigate_lb_real_server_status

### ISSUE THREAD

**Issue by bjolivot** [bluecmd/fortigate_exporter#93]
Hello, your exporter seem's great! saddly I can't use it :(

I have a duplicated entry error message in HA setup (fw nodes have different names)

The problem is reported for these keys:

- fortigate_lb_real_server_mode
- fortigate_lb_real_server_status
- fortigate_lb_real_server_rtt_seconds
- fortigate_lb_real_server_processed_bytes_total
- fortigate_lb_real_server_active_sessions

Could you help me ?

Partial error output :

An error has occurred while serving metrics:

54 error(s) occurred:
* collected metric "fortigate_lb_real_server_mode" { label:<name:"id" value:"0" > label:<name:"mode" value:"active" > label:<name:"vdom" value:"root" > label:<name:"virtual_server" value:"WEBSERVER_VIP1" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "fortigate_lb_real_server_mode" { label:<name:"id" value:"0" > label:<name:"mode" value:"standby" > label:<name:"vdom" value:"root" > label:<name:"virtual_server" value:"WEBSERVER_VIP1" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "fortigate_lb_real_server_mode" { label:<name:"id" value:"0" > label:<name:"mode" value:"disabled" > label:<name:"vdom" value:"root" > label:<name:"virtual_server" value:"WEBSERVER_VIP1" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "fortigate_lb_real_server_status" { label:<name:"id" value:"0" > label:<name:"state" value:"up" > label:<name:"vdom" value:"root" > label:<name:"virtual_server" value:"WEBSERVER_VIP1" > gauge:<value:1 > } was collected before with the same name and label values
* collected metric "fortigate_lb_real_server_status" { label:<name:"id" value:"0" > label:<name:"state" value:"down" > label:<name:"vdom" value:"root" > label:<name:"virtual_server" value:"WEBSERVER_VIP1" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "fortigate_lb_real_server_status" { label:<name:"id" value:"0" > label:<name:"state" value:"unknown" > label:<name:"vdom" value:"root" > label:<name:"virtual_server" value:"WEBSERVER_VIP1" > gauge:<value:0 > } was collected before with the same name and label values

**Comment by aiiksveryown** [comment]
I have just encountered this issue after updating to the latest image of fortigate_exporter.
I have two devices. 1. OS v6.2.3 has this issue. 2. OS v6.4.4 does not have any issues.
So no metrics from fortigate 1. Ideas?

**Comment by bjolivot** [comment]
I'm using 6.0.5

**Comment by secustor** [comment]
Hmm this usually happens only if both nodes have the same virtual name. 

Can you provide the API response from `api/v2/monitor/firewall/load-balance?vdom=*&start=0&count=1000`? 
You can censor it if necessary. 

It should look like this: https://github.com/bluecmd/fortigate_exporter/blob/master/testdata/fw-loadbalancers.jsonnet

**Comment by aiiksveryown** [comment]
I deleted the Virtual Server on the FG (It was not in use) and now it works.

**Comment by bjolivot** [comment]
Hello @secustor 
here is API response

I censored server names & public IPs but everytime I used "replace all" so it keeps name and ip reuse intact.

Thank you for your help :)


[
  {
    "http_method":"GET",
    "results":[
      {
        "virtual_server_name":"SERVER_A_VIP1",
        "virtual_server_ip":"1.1.1.1",
        "virtual_server_port":80,
        "list":[
          {
            "real_server_ip":"172.16.21.71",
            "real_server_port":80,
            "mode":"active",
            "status":"up",
            "monitor_events":0,
            "active_sessions":0,
            "RTT":"<1",
            "bytes_processed":15229619
          },
          {
            "real_server_ip":"172.16.21.72",
            "real_server_port":80,
            "mode":"active",
            "status":"up",
            "monitor_events":0,
            "active_sessions":0,
            "RTT":"<1",
            "bytes_processed":15161544
          }
        ]
      },
      {
        "virtual_server_name":"SERVER_B_VIP1",
        "virtual_server_ip":"2.2.2.2",
        "virtual_server_port":80,
        "list":[
          {
            "real_server_ip":"172.16.12.11",
            "real_server_port":80,
            "mode":"active",
            "status":"up",
            "monitor_events":453,
            "active_sessions":29,
            "RTT":"<1",
            "bytes_processed":1078930596
          },
          {
            "real_server_ip":"172.16.12.12",
            "real_server_port":80,
            "mode":"active",
            "status":"up",
            "monitor_events":319,
            "active_sessions":30,
            "RTT":"<1",
            "bytes_processed":599401634
          },
          {
            "real_server_ip":"172.16.12.13",
            "real_server_port":80,
            "mode":"active",
            "status":"up",
            "monitor_events":277,
            "active_sessions":31,
            "RTT":"<1",
            "bytes_processed":210000980
          }
        ]
      },
      {
        "virtual_server_name":"SERVER_C_VIP1",
        "virtual_server_ip":"2.2.2.2",
        "virtual_server_port":443,
        "list":[
          {
            "real_server_ip":"172.16.12.11",
            "real_server_port":443,
            "mode":"active",
            "status":"up",
            "monitor_events":453,
            "active_sessions":1195,
            "RTT":"<1",
            "bytes_processed":2924680546
          },
          {
            "real_server_ip":"172.16.12.12",
            "real_server_port":443,
            "mode":"active",
            "status":"up",
            "monitor_events":319,
            "active_sessions":1158,
            "RTT":"<1",
            "bytes_processed":1321522472
          },
          {
            "real_server_ip":"172.16.12.13",
            "real_server_port":443,
            "mode":"active",
            "status":"up",
            "monitor_events":271,
            "active_sessions":1202,
            "RTT":"<1",
            "bytes_processed":535563650
          }
        ]
      },
      {
        "virtual_server_name":"___SERVER_D___VIP1",
        "virtual_server_ip":"1.1.1.1",
        "virtual_server_port":443,
        "list":[
          {
            "real_server_ip":"172.16.21.71",
            "real_server_port":443,
            "mode":"active",
            "status":"up",
            "monitor_events":0,
            "active_sessions":0,
            "RTT":"<1",
            "bytes_processed":14394632
          },
          {
            "real_server_ip":"172.16.21.72",
            "real_server_port":443,
            "mode":"active",
            "status":"up",
            "monitor_events":0,
            "active_sessions":0,
            "RTT":"<1",
            "bytes_processed":14361160
          }
        ]
      }
    ],
    "vdom":"root",
    "path":"firewall",
    "name":"load-balance",
    "status":"success",
    "serial":"FG0**********",
    "version":"v6.0.5",
    "build":268
  }
]

**Comment by secustor** [comment]
K, I see the problem now.      
A field we are using to identify the physical servers `real_server_id` is missing from that response. 

That combined with the comment from @aiiksveryown  suggests they have introduced this field in v6.3 or v6.4.  

Is upgrading the OS version for you an option? I would be helpful to find out from which version the field is included.

**Comment by bjolivot** [comment]
Hello @secustor 
I can't upgrade production firewalls (that's just one cluster and i have more of them) just to use an exporter.
I understand the 6.0.x branch is old but could I know if you plan to make an update or do I need to write my own exporter ?

**Comment by bluecmd** [comment]
@bjolivot We should certainly fix this in the exporter, it's just that we're doing this on volunteer basis and we don't have this problem and thus can't reproduce the issue.

The absolute fastest way to fix these issues is to open a PR with a new test that tests the failing case, together with a fix. Then we can merge it straight away.

That said, the fix should be simple given the data present in the thread.

**Comment by secustor** [comment]
I think the best way would be to simply skip this metrics if an API version is detected which  is not compatible, as we are breaking in that case not other users. 

To implement this we need to know when this has been implemented.

**Comment by bluecmd** [comment]
@secustor In that case, what do you think of just dropping the metric if the `.._id` field doesn't exist? I.e. look for the field itself in the data instead of inferring its existence based on version.

**Comment by bjolivot** [comment]
On a 6.0.5 fortigate, the filed virtual_server_name must be unique so adding that field could solve my problem.
I'm sorry I can't help more, I only code python, not golang :(

**Comment by secustor** [comment]
@bluecmd  I think it is fine as quick fix, but we should do this API version based as there are probably more of these changes in minor versions.

This could be part of bigger refactoring as `probe.go` is becoming quite huge.

**Comment by bjolivot** [comment]
Thanks for the update, 
I will work on my own exporter as I need loadbalancer metrics with 6.0 and 6.2.
