### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by mdegouw** [bluecmd/fortigate_exporter#97]
After setting up the exporter the fortigate keeps using more and more memory until it crashes, is this a known issue, and is there a fix/workaround?

Fortigate 60F

![image](https://user-images.githubusercontent.com/3748069/123390102-d62ec000-d59a-11eb-99b1-babebd1fc98f.png)

**Comment by bluecmd** [comment]
Hello!

Yes, indeed for some versions of FortiOS there are known memory leaks: https://github.com/bluecmd/fortigate_exporter#known-issues

The recommended version train right now is 6.4 - we haven't had any issues with it and some metrics require that version or newer.

**Comment by mdegouw** [comment]
We currently have 2 6.4.0 FortiGate's with this issue.

We also have a 6.4.6 Fortigate, i will monitor that one aswell to see if it has the same problems.

**Comment by mdegouw** [comment]
Just read in #62 that it looks like this issue is solved from at least 6.4.5.
Unfortunately we do not have the time to upgrade one version at a time to give you updated information, but it looks like you should recommend 6.4.5 or higher as the leak is still present in 6.4.0
