### ISSUE TITLE
cannot unmarshal !!map into config.Token Latest docker version

### ISSUE THREAD

**Issue by aiiksveryown** [bluecmd/fortigate_exporter#98]
The config file is the same as in example, and worked with a previous version. (1.4.2) Now the docker container won't start, full error below. I have 2 keys. I have reinstalled old version for now.

Failed to parse API authentication map file: yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into config.Token
  line 4: cannot unmarshal !!map into config.Token

**Comment by bluecmd** [comment]
Hi!

Hm, I am running 1.5.0 locally with:
```
/home/fortigate-exporter/fortigate_exporter -auth-file /home/fortigate-exporter/fortigate-key.yaml
```

and my config:

```yaml
"https://fw.xyz.dev":
  token: 'asdasdasd'
```

Is your different?

Can you post your config with the hostnames and tokens censored?

**Comment by ordinaryman9394** [comment]
I ran into the same issue and finally got it working after hours. Try this:

"https://10.10.10.1":
  "abcdefg"

**Comment by bluecmd** [comment]
Reproduced:

```
bluecmd@debian:~$ cat /tmp/config/fortigate-key.yaml
"https://fortigate.s6.network":
  token: "asd"
bluecmd@debian:~$ docker run  -v /tmp/config:/config/ quay.io/bluecmd/fortigate_exporter
2021/07/10 18:13:47 FortigateExporter (devel) ( (no hash) )
2021/07/10 18:13:47 Failed to parse API authentication map file: yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into config.Token
bluecmd@debian:~$ docker run  -v /tmp/config:/config/ quay.io/bluecmd/fortigate_exporter:v1.5.0
2021/07/10 18:13:50 FortigateExporter (devel) ( (no hash) )
2021/07/10 18:13:50 Loaded 1 API keys
2021/07/10 18:13:50 Fortigate exporter running, listening on ":9710"
```

I also see that our Docker builds lack version information.
Ping @secustor FYI.

**Comment by bluecmd** [comment]
Fix in https://github.com/bluecmd/fortigate_exporter/pull/107
